import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { KeykitProvider } from "@keykithq/sdk/next";
import { useTranslate } from "@keykithq/sdk/react";
import keykitConfig from "../keykit.config";
import { LocaleSwitcher } from "./locale-switcher";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  const { locale } = useTranslate();

  return (
    <html
      lang={locale}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <KeykitProvider>{children}</KeykitProvider>
      </body>
    </html>
  );
}
